Searching.Site/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.Web.WebApi;

namespace Searching.Site.Controllers
{

    public class NewsController : UmbracoApiController
    {
        [HttpGet]
        public IEnumerable<NewsItem> GetNewsList()
        {
            // Get the news content node
            var newsNode = Umbraco.ContentAtRoot().DescendantsOrSelfOfType("news").FirstOrDefault();

            // Get the news items
            var newsItems = newsNode.Children<IPublishedContent>().Select(x => new NewsItem
            {
                Id = x.Id,
                PageTitle = x.Value<string>("pageTitle"),
                PageSummary = x.Value<string>("summary"),
                PageImage = x.Value<IPublishedContent>("image").Url(),
                Date = x.Value<DateTime>("date")
            });

            // Return the news items as JSON
            return newsItems;
        }

        [HttpGet]
        public NewsItem GetNewsDetail(int id)
        {
            // Get the news item by id
            var newsItem = Umbraco.Content(id);

            // Return the news item as JSON
            return new NewsItem
            {
                Id = newsItem.Id,
                PageTitle = newsItem.Value<string>("pageTitle"),
                PageSummary = newsItem.Value<string>("summary"),
                PageContent = newsItem.Value<string>("bodyText"),
                PageImage = newsItem.Value<IPublishedContent>("image").Url(),
                Date = newsItem.Value<DateTime>("date")
            };
        }
    }

    public class NewsItem
    {
        public int Id { get; set; }
        public string PageTitle { get; set; }
        public string PageSummary { get; set; }
        public string PageContent { get; set; }
        public string PageImage { get; set; }
        public DateTime Date { get; set; }
    }

}

Searching.Site/Controllers/SearchPageController.cs
using Searching.Site.Models;
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using Searching.Site.Models.ViewModels;
using Searching.Site.Services;
using System.Collections.Generic;

namespace Searching.Site.Controllers
{
    public class SearchPageController : RenderMvcController
    {
        private readonly ISearchService _searchService;
        private readonly IDataTypeValueService _dataTypeValueService;
        public string[] DocTypeAliases { get; set; }

        public SearchPageController(ISearchService searchService, IDataTypeValueService dataTypeValueService)
        {
            _searchService = searchService;
            _dataTypeValueService = dataTypeValueService;
            DocTypeAliases = new[] {"blogpost", "contentPage", "newsItem"};
        }

        public ActionResult Index(ContentModel model, string query, string page, string category)
        {
            var searchPageModel = new SearchContentModel(model.Content);

            IEnumerable<SelectListItem> categories = 
                _dataTypeValueService.GetItemsFromValueListDataType("[MULTICHECKBOXLIST] Category List", null);

            var searchViewModel = new SearchViewModel()
            {
                Query = query,
                Category = category,
                Page = page,
                Categories = categories
            };

            if(!int.TryParse(page, out var pageNumber))
            {
                pageNumber = 1;
            }

            var searchResults = _searchService.GetPageOfContentSearchResults(query, category,
                pageNumber, out var totalItemCount, DocTypeAliases);

            searchPageModel.SearchViewModel = searchViewModel;
            searchPageModel.SearchResults = searchResults;
            
            return CurrentTemplate(searchPageModel);
        }
    }
}

Searching.Site/Controllers/Surface/SearchSurfaceController.cs
using System.Collections.Generic;
using Searching.Site.Models.ViewModels;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using System.Collections.Specialized;

namespace Searching.Site.Controllers.Surface
{
    public class SearchSurfaceController : SurfaceController
    {
        public ActionResult SubmitForm(SearchViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            var queryString = new NameValueCollection();

            if(!string.IsNullOrWhiteSpace(model.Query))
            {
                queryString.Add("query", model.Query);
            }

            if(!string.IsNullOrWhiteSpace(model.Category))
            {
                queryString.Add("category", model.Category);
            }

            if (!string.IsNullOrWhiteSpace(model.Page))
            {
                queryString.Add("page", model.Page);
            }

            return RedirectToCurrentUmbracoPage(queryString);
        }

        public ActionResult RenderForm(SearchViewModel model)
        {
            return PartialView("Partials/SearchForm", model);
        }
    }
}

Searching.Site/Views/Blog.cshtml
@using ContentModels = Umbraco.Web.PublishedModels;
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Blog>
@using Umbraco.Web;
@{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">

    <div class="container">
        @Umbraco.RenderMacro("latestBlogposts",
            new
            {
                numberOfPosts = Model.HowManyPostsShouldBeShown,
                startNodeId = Model.Id
            })
        @{
        }
    </div>

</section>

Searching.Site/Views/Blogpost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Blogpost>
@using ContentModels = Umbraco.Web.PublishedModels;
    @{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">
    <div class="container">
        <article>
            <div class="blogpost-meta">
                <small class="blogpost-date">@Model.CreateDate.ToShortDateString()</small>
                <span class="blogpost-cat">
                    @Html.Partial("~/Views/Partials/CategoryLinks.cshtml", Model.Categories)
                </span>
            </div>
            <h3>@Model.Excerpt</h3>
            @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
            <!-- todo: implement discus comments -->
        </article>
    </div>
</section>

Searching.Site/Views/NewsPage.cshtml
<!-- NewsPage.cshtml -->
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Umbraco.Core.Models.PublishedContent
@using Umbraco.Web.PublishedModels
@{
    Layout = "master.cshtml";
}

<h1>News Detail Page</h1>

Searching.Site/Views/Person.cshtml
@{
	Layout = "master.cshtml";
}
<p>Nothing to see, but we could make a lesson to display a person</p>

Searching.Site/Views/Products.cshtml
@inherits UmbracoViewPage<ContentModels.Products>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")
<section class="section">

    <div class="container">

        <!-- todo: implement category selector -->
        <!--
        <nav class="nav-bar nav-bar--center nav-bar--air-bottom">
            <a class="nav-link nav-link--black nav-link--active" href="">All</a>
            <a class="nav-link nav-link--black" href="">Clothing</a>
            <a class="nav-link nav-link--black" href="">Instruments</a>
            <a class="nav-link nav-link--black" href="">Accessories</a>
            <a class="nav-link nav-link--black" href="">Other</a>
        </nav>
        -->
        <div class="product-grid">
            @if (Model.FeaturedProducts != null)
            {
                foreach (Product product in Model.FeaturedProducts)
                {
                    <a href="@product.Url" class="product-grid__item" style="background-image: url('@product.Photos.Url')">
                        <div class="product-grid__item__overlay">
                            <div class="product-grid__item__name">@product.ProductName</div>
                            <div class="product-grid__item__price">@Model.DefaultCurrency @product.Price.ToString("F")</div>
                        </div>
                    </a>
                }
            }
        </div>
    </div>

</section>

Searching.Site/Views/contact.cshtml
@inherits UmbracoViewPage<Contact>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";


    var coordinates = Model.MapCoordinates.ToString().Split(',');

    var latitude = coordinates[0];
    var longitude = coordinates[1];
    var zoomLevel = coordinates[2];

    // Build the coordinates string
    var coordinatesString = longitude + "," + latitude + "," + longitude + "," + latitude;
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")
<section class="section">
    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <h2>@Model.MapHeader</h2>
                <iframe width="550"
                        height="400"
                        frameborder="0"
                        scrolling="no"
                        marginheight="0"
                        marginwidth="0"
                        src="https://www.openstreetmap.org/export/embed.html?bbox=@coordinatesString&amp;layer=mapnik&amp;marker=@Model.MapCoordinates"
                        style="border: 1px solid black">
                </iframe>

                <br />

                <small>
                    <a href="https://www.openstreetmap.org/?mlat=@latitude&amp;mlon=@longitude#map=@zoomLevel/@latitude/@longitude&amp;layers=N">View Larger Map</a>
                </small>
            </div>

            <div class="col-md-6">
                <h2>@Model.ContactFormHeader</h2>
                @Model.ContactIntro
                <p class="compat-msg">
        <em>Umbraco Forms</em> is required to render this form.It's a breeze to install, all you have to do is
        go to the<em> Umbraco Forms</em> section in the back office and click Install, that's it! :) 
        <br /><br />
        <a href="/umbraco/#/forms" class="button button--border--solid">Go to Back Office and install Forms</a>
        <!-- When Umbraco Forms is installed, uncomment this line -->
        @* @Umbraco.RenderMacro("renderUmbracoForm", new {FormGuid=Model.ContactForm.ToString()}) *@
        </p>
            </div>

        </div>
    </div>
</section>

Searching.Site/Views/contentPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ContentPage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
}

@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">

    <div class="container">

        <div class="col-md-3">
            <nav class="nav-bar nav-bar--list">
                @Html.Partial("~/Views/Partials/Navigation/SubNavigation.cshtml")
            </nav>
        </div>

        <div class="col-md-9">
            <article>
                @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
            </article>
        </div>
    </div>

</section>

Searching.Site/Views/home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage


@{
    Layout = "master.cshtml";
}

<hr>
<h4>Haberler</h4>
<div class="list-group" id="news-ListGroup">

</div>

Searching.Site/Views/master - 00.cshtml
@using Umbraco.Core.PropertyEditors
@inherits UmbracoViewPage
@{
    Layout = null;
    // Get basic design settings from the homepage
    var home = (Home)Model.Root();
    var font = home.Font;
    var colorTheme = home.ColorTheme;
}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>@Model.Name - @home.Sitename</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="@Url.Content("~/css/umbraco-starterkit-style.css")" />
    @RenderSection("Header", required: false)
</head>

<body class="frontpage theme-font-@font theme-color-@colorTheme">
    <div class="mobile-nav">
        <nav class="nav-bar">
            @Html.Partial("~/views/partials/navigation/topNavigation.cshtml")
        </nav>
    </div>

    <header class="header">

        <div class="logo">
            @if (home.SiteLogo != null && !string.IsNullOrEmpty(home.SiteLogo.Url))
            {
                <div class="nav-link--home">
                    <img class="logo-image" src="@home.SiteLogo.Url" alt="@home.Sitename">
                </div>
            }
            else
            {
                <a class="nav-link nav-link--home nav-link--home__text logo-text" href="/">@home.Sitename</a>
            }
        </div>

        <nav class="nav-bar top-nav">
            @Html.Partial("~/Views/Partials/Navigation/TopNavigation.cshtml")
        </nav>

        <div class="mobile-nav-handler">
            <div class="hamburger lines" id="toggle-nav">
                <span></span>
            </div>
        </div>

    </header>

    <main>
        @RenderBody()
    </main>

    <footer class="section--themed">
        <div class="container">
            <div class="row">
                <div class="col-md-12 ta-center">
                    @home.FooterAddress
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <script src="@Url.Content("~/scripts/umbraco-starterkit-app.js")"></script>

</body>

</html>

Searching.Site/Views/master - 02.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.PublishedModels.Home>

@{
    Layout = null;
}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Live Search Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="~/css/dev.css" />
</head>


<body>

    <header>
        <div class="container py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">

                <div class="col-6"></div>

                <div class="col-6 d-flex justify-content-end align-items-center">

                    <!-- Trigger Modal -->
                    <a class="link-secondary" href="#" aria-label="Search" data-bs-toggle="modal" data-bs-target="#SearchModal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5" /><path d="M21 21l-5.2-5.2" /></svg>
                    </a>

                </div>
            </div>

        </div>
    </header>

    <main>
        <div class="container">
            @RenderBody()

            <section id="search-section">

                <form id="search-form" action="@Url.Action("SubmitSearchForm", "SearchSurface")" method="post">
                    <input type="text" name="query" id="search-query" placeholder="Enter your search term...">
                    <button type="submit">Search</button>
                </form>

                <div id="search-results-container">
                    <!-- Burada arama sonuçlarını gösterecek olan partial view çağrılır -->
                    @if (ViewData["SearchViewModel"] != null)
                    {
                        var model = ViewData["SearchViewModel"] as Searching.Site.Models.ViewModels.SearchViewModel;
                    @Html.Partial("~/Views/Partials/SearchResults.cshtml", model)
                    }
                </div>
            </section>
        </div>
    </main>

    <footer>
        <div class="container">

        </div>
    </footer>



    <!-- Search Modal -->
    <div class="modal fade" id="SearchModal" tabindex="-1" aria-labelledby="SearchModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">

                <div class="modal-header">

                    <form class="form" id="search-form" action="@Url.Action("SubmitSearchForm", "SearchSurface")" method="post">
                        <i class="fa fa-search"></i>
                        <input type="text" name="query" id="search-query" class="form-control form-input" placeholder="Enter your search term...">
                        @*<button type="submit">Search</button>*@
                    </form>

                </div>

                <div class="modal-body">

                    <ul id="SearchResults">

                       <!-- Burada arama sonuçlarını gösterecek olan partial view çağrılır -->
                       @if (ViewData["SearchViewModel"] != null)
                       {
                           var model = ViewData["SearchViewModel"] as Searching.Site.Models.ViewModels.SearchViewModel;
                       @Html.Partial("~/Views/Partials/SearchResults.cshtml", model)
                       }

                    </ul>

                </div>

                <div class="modal-footer">
                    <p>1453 kayıt bulundu.</p>
                </div>

            </div>
        </div>
    </div>



    <script src="~/scripts/JQuery/3.7.0/jquery-3.7.0.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@("@")popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@("@")5.3.3/dist/js/bootstrap.min.js"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>


    <script>
        $(document).ready(function () {
            var searchTimeout = null;

            // Arama ikonuna tıklandığında modal pencereyi göster
            $("#search-icon").click(function () {
                $("#search-modal").show();
                $("#search-query").focus(); // İmleci arama çubuğuna odakla
            });

            // Modal pencerenin dışına tıklandığında kapat
            $(window).click(function (event) {
                if (event.target.id === "search-modal") {
                    $("#search-modal").hide();
                }
            });

            // Kullanıcı arama çubuğuna yazmaya başladığında
            $("#search-query").on("input", function () {
                var query = $(this).val();

                // Önceki AJAX isteğini iptal et
                clearTimeout(searchTimeout);

                // 3 veya daha fazla karakter girildiyse arama isteği gönder
                if (query.length >= 3) {
                    searchTimeout = setTimeout(function () {
                        $.ajax({
                            url: "/Umbraco/Api/Search/GetSearchResults", // API URL'nizi güncelleyin
                            type: "GET",
                            data: { query: query },
                            dataType: "json",
                            success: function (data) {
                                // Arama sonuçlarını listele
                                displaySearchResults(data.Results);
                            },
                            error: function (xhr, status, error) {
                                console.error(error);
                                // Hata durumunda yapılacak işlemler (örneğin, hata mesajı göster)
                                $("#SearchResults").html(
                                    "<li>Arama sonuçları alınamadı.</li>"
                                );
                            },
                        });
                    }, 300); // 300 milisaniye gecikme (istekleri azaltmak için)
                } else {
                    // Arama sonuçlarını temizle
                    $("#SearchResults").empty();
                }
            });

            // Arama sonuçlarını listeleme işlevi
            function displaySearchResults(results) {
                var $searchResults = $("#SearchResults");
                $searchResults.empty();

                if (results.length > 0) {
                    $.each(results, function (index, result) {
                        $searchResults.append(
                            "<li><a href='" + result.Url + "'>" + result.Name + "</a></li>"
                        );
                    });
                } else {
                    $searchResults.append("<li>Sonuç bulunamadı.</li>");
                }
            }
        });
    </script>


</body>

</html>

Searching.Site/Views/master - 03.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@{
    Layout = null;
}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Live Search Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="~/css/dev.css" />
</head>


<body>

    <header>
        <div class="container py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">

                <div class="col-6"></div>

                <div class="col-6 d-flex justify-content-end align-items-center">

                    <!-- Trigger Modal -->
                    <a class="link-secondary" href="#" aria-label="Search" data-bs-toggle="modal" data-bs-target="#SearchModal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5" /><path d="M21 21l-5.2-5.2" /></svg>
                    </a>

                </div>
            </div>

        </div>
    </header>

    <main>
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <footer>
        <div class="container">

        </div>
    </footer>



    <!-- Search Modal -->
    <div class="modal fade" id="SearchModal" tabindex="-1" aria-labelledby="SearchModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">

                <div class="modal-header">

                    <form class="form" id="search-form" action="@Url.Action("SubmitSearchForm", "SearchSurface")" method="post">
                        <i class="fa fa-search"></i>
                        <input type="text" name="query" id="search-query" class="form-control form-input" placeholder="Enter your search term...">
                        @*<button type="submit">Search</button>*@
                    </form>

                </div>

                <div class="modal-body">

                    <div id="SearchResults" class="list-group">

                       <!-- Burada arama sonuçlarını gösterecek olan partial view çağrılır -->
                       @if (ViewData["SearchViewModel"] != null)
                       {
                            var model = ViewData["SearchViewModel"] as Searching.Site.Models.ViewModels.SearchViewModel;
                            @Html.Partial("~/Views/Partials/SearchResults.cshtml", model)
                       }

                    </div>

                </div>

                <div class="modal-footer">
                    <p>1453 kayıt bulundu.</p>
                </div>

            </div>
        </div>
    </div>



    <script src="~/scripts/JQuery/3.7.0/jquery-3.7.0.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@("@")popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@("@")5.3.3/dist/js/bootstrap.min.js"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>


    <script>
        $(document).ready(function () {
            var searchTimeout = null;

            // Arama ikonuna tıklandığında modal pencereyi göster
            $("#search-icon").click(function () {
                $("#search-modal").show();
                $("#search-query").focus(); // İmleci arama çubuğuna odakla
            });

            // Modal pencerenin dışına tıklandığında kapat
            $(window).click(function (event) {
                if (event.target.id === "search-modal") {
                    $("#search-modal").hide();
                }
            });

            // Kullanıcı arama çubuğuna yazmaya başladığında
            $("#search-query").on("input", function () {
                var query = $(this).val();

                // Önceki AJAX isteğini iptal et
                clearTimeout(searchTimeout);

                // 3 veya daha fazla karakter girildiyse arama isteği gönder
                if (query.length >= 3) {
                    searchTimeout = setTimeout(function () {
                        $.ajax({
                            url: "/Umbraco/Surface/SearchSurface/SubmitSearchForm", // Doğru API URL'sini buraya girin
                            type: "POST", // Form verilerini POST olarak gönderiyoruz
                            data: $("#search-form").serialize(), // Form verilerini serileştiriyoruz
                            dataType: "html", // Dönen veri tipi olarak html kullanıyoruz, çünkü partial view dönecek
                            success: function (data) {
                                $("#SearchResults").html(data); // Başarılı olursa sonuçları container içine ekliyoruz
                            },
                            error: function (xhr, status, error) {
                                console.error(error);
                                // Hata durumunda yapılacak işlemler (örneğin, hata mesajı göster)
                                $("#SearchResults").html("<p>Arama sonuçları alınamadı.</p>");
                            },
                        });
                    }, 300); // 300 milisaniye gecikme (istekleri azaltmak için)
                } else {
                    // Arama sonuçlarını temizle
                    $("#SearchResults").empty();
                }
            });

            // Arama sonuçlarını listeleme işlevi
            function displaySearchResultsModal(results) {
                var $searchResults = $("#SearchResultsModal");
                $searchResults.empty();

                // results değişkeni tanımlı ve boş olmayan bir dizi mi kontrol ediyoruz
                if (results && Array.isArray(results) && results.length > 0) {
                    $.each(results, function (index, result) {
                        $searchResults.append(
                            "<li><a href='" + result.Url + "'>" + result.Name + "</a></li>"
                        );
                    });
                    $("#search-results-count").text(results.length + " results found.");
                } else {
                    $searchResults.append("<li>No results found.</li>");
                    $("#search-results-count").text("0 results found.");
                }
            }
        });
    </script>




    <!-- API ile Search Yapmak için yorum satırlarını kaldır. Yukarıyı da yorum satırına çevir. -->
    <script>
        //$(document).ready(function () {
        //    var searchTimeout = null;

        //    // Kullanıcı arama çubuğuna yazmaya başladığında
        //    $("#search-query").on("input", function () {
        //        var query = $(this).val();

        //        // Önceki AJAX isteğini iptal et
        //        clearTimeout(searchTimeout);

        //        // 3 veya daha fazla karakter girildiyse arama isteği gönder
        //        if (query.length >= 3) {
        //            searchTimeout = setTimeout(function () {
        //                $.ajax({
        //                    url: "/Umbraco/Api/SearchApi/GetSearchResults",
        //                    type: "GET",
        //                    data: { query: query },
        //                    dataType: "json",
        //                    success: function (data) {
        //                        displaySearchResults(data);
        //                    },
        //                    error: function (xhr, status, error) {
        //                        console.error(error);
        //                        $("#SearchResults").html("<li>Arama sonuçları alınamadı.</li>");
        //                    }
        //                });
        //            }, 300); // 300 milisaniye gecikme (istekleri azaltmak için)
        //        } else {
        //            $("#SearchResults").empty();
        //        }
        //    });

        //    // Arama sonuçlarını listeleme işlevi
        //    function displaySearchResults(results) {
        //        var $searchResults = $("#SearchResults");
        //        $searchResults.empty();

        //        if (results.length > 0) {
        //            $.each(results, function (index, result) {
        //                $searchResults.append(
        //                    "<li><a href='" + result.Url + "'>" + result.Name + "</a></li>"
        //                );
        //            });
        //        } else {
        //            $searchResults.append("<li>Sonuç bulunamadı.</li>");
        //        }
        //    }
        //});

    </script>


</body>

</html>